// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdhOlepjxAswpQHnXzu-_439QzoakPXc',
    appId: '1:944290577116:web:0c8e5daa3f7b2c046a9219',
    messagingSenderId: '944290577116',
    projectId: 'comprovaapp',
    authDomain: 'comprovaapp.firebaseapp.com',
    storageBucket: 'comprovaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyC4ARKwqzdxh1YXNWBv_6Ba5JEXitlm0',
    appId: '1:944290577116:android:81cd0f20736200fc6a9219',
    messagingSenderId: '944290577116',
    projectId: 'comprovaapp',
    storageBucket: 'comprovaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfpQ9sYruqPZ4Q7oWssNHWO0ncPpHWd-I',
    appId: '1:944290577116:ios:d8de7735e0689a2a6a9219',
    messagingSenderId: '944290577116',
    projectId: 'comprovaapp',
    storageBucket: 'comprovaapp.firebasestorage.app',
    iosBundleId: 'com.example.comprovapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfpQ9sYruqPZ4Q7oWssNHWO0ncPpHWd-I',
    appId: '1:944290577116:ios:d8de7735e0689a2a6a9219',
    messagingSenderId: '944290577116',
    projectId: 'comprovaapp',
    storageBucket: 'comprovaapp.firebasestorage.app',
    iosBundleId: 'com.example.comprovapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjdhOlepjxAswpQHnXzu-_439QzoakPXc',
    appId: '1:944290577116:web:c9bac2545e0ca9036a9219',
    messagingSenderId: '944290577116',
    projectId: 'comprovaapp',
    authDomain: 'comprovaapp.firebaseapp.com',
    storageBucket: 'comprovaapp.firebasestorage.app',
  );
}
